services:
    periodic_table:
        class: AppBundle\Service\PeriodicTable
        arguments: [@doctrine.orm.entity_manager,@logger,@validate]
        tags:
          - { name: monolog.logger, channel: cData }
    exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments: [@logger]
        tags:
          - {name: kernel.event_listener, event: kernel.exception, method: onKernelException }
          - { name: monolog.logger, channel: exception }

    soap_request:
        class: AppBundle\Service\HandleRequest
        arguments: [@periodic_table,@logger, @doctrine.orm.entity_manager, @validate]

    validate:
        class: AppBundle\Service\Validator
        arguments: [@doctrine.orm.entity_manager,@fos_user.user_manager, @security.encoder_factory]
    soap_response:
        class: AppBundle\Service\CreateResponse
        arguments: []
